// Constantes pour les plans de pricing
export const pricingPlans = [
  {
    id: 1,
    name: 'Gratuit',
    description: 'Parfait pour démarrer',
    price: 0,
    currency: '€',
    period: '/mois',
    highlighted: false,
    features: [
      'Jusqu\'à 10 GB de stockage',
      'Notes illimitées',
      'Partage basique',
      'Support par email',
      'Synchronisation sur 2 appareils',
      'Accès aux templates',
    ],
    cta: 'Commencer maintenant',
    ctaStyle: 'secondary',
  },
  {
    id: 2,
    name: 'Premium',
    description: 'Pour les professionnels',
    price: 9.99,
    currency: '€',
    period: '/mois',
    highlighted: true,
    features: [
      'Stockage illimité',
      'Notes illimitées',
      'Partage avancé avec permissions',
      'Support prioritaire',
      'Synchronisation sur tous les appareils',
      'Accès à tous les templates',
      'Historique des versions (30 jours)',
      'Collaboration en temps réel',
      'Export en plusieurs formats',
    ],
    cta: 'Essayer gratuitement',
    ctaStyle: 'primary',
  },
  {
    id: 3,
    name: 'Équipe',
    description: 'Pour les organisations',
    price: 99,
    currency: '€',
    period: '/an',
    highlighted: false,
    features: [
      'Tous les avantages Premium',
      'Jusqu\'à 100 utilisateurs',
      'Gestion d\'équipe avancée',
      'Contrôle d\'accès granulaire',
      'Support dédié',
      'API access',
      'Audit logs',
      'Intégrations personnalisées',
      'SLA garantie',
    ],
    cta: 'Nous contacter',
    ctaStyle: 'secondary',
  },
];
